_target_: modelling.src.models.aes.grugru.model.GRUVAE
config:
  _target_: modelling.src.models.aes.grugru.config.GRUVAEConfig
  vocab_size: 29
  embedding_dim: 100
  padding_idx: 0
  latent_dim: 64
  encoder_hidden_size: 256
  encoder_num_layers: 4
  encoder_bidirectional: true
  encoder_dropout: 0.1
  decoder_hidden_size: 256
  decoder_num_layers: 4
  decoder_dropout: 0.1
  kl_beta: 1.0
  ignore_index: 0
  label_smoothing: 0.0
